### ISSUE TITLE
 In source code release v1.6.0 is still Adminer v4.2.0

### ISSUE THREAD

**Issue by buffus** [dg/adminer-custom#14]
Hi, [Adminer updated to 4.2.**1**](https://github.com/dg/adminer-custom/commit/7b10dba2243cb222b6327c035f34865acdf70a87), but in [source code release v1.6.0](https://github.com/dg/adminer-custom/releases/tag/v1.6.0) is still Adminer 4.2.**0**. Excuse me, but I’m confused.

**Comment by mhujer** [comment]
It looks like that 1.6.1 contains Adminer 4.2.1 so this one can be closed.

**Comment by buffus** [comment]
It's true. Thank you.
