### ISSUE TITLE
unable to write any thing in sql command text box

### ISSUE THREAD

**Issue by vivektewari24** [dg/adminer-custom#16]
not working unable to write anything in SQL command box. cursor goes out of focus with every key hit

**Comment by dg** [comment]
What the browser are you using?

**Comment by vivektewari24** [comment]
its chrome Version 48.0.2564.116 m
latest

**Comment by dg** [comment]
I do not know what it may be, it works normally to me. Any extension?

**Comment by vivektewari24** [comment]
Yes! Grammarly..... will let you know whether its working or not after removing grammarly

**Comment by vivektewari24** [comment]
Hi, Just checked that its working fine.... culprit was only Grammarly extension
