### ISSUE TITLE
Nezobrazující se ikony v menu tabulek

### ISSUE THREAD

**Issue by martinsifra** [dg/adminer-custom#18]
Ve verzi 4.2.2 se menu tabulek vypisovalo pomocí `<p>`. V verzi 4.3 se vypisuje pomocí seznamu `<ul><li>`. CSS s ikonkou jsou ale navázané na ty odstavce. Pull request pošlu ráno.

EDIT: Večer.

**Comment by martinsifra** [comment]
Zavírám. Problém vznikl v Admineru, kde někdo změnil výpis z <p> na <ul> a rozbil to. Měl by na to kouknout nějaký kodér, ať to má úroveň. Bohužel do Admineru jsou posílat pouze pull requesty bez issue.

**Comment by martinsifra** [comment]
Je to tady, až dostreamuješ, je to tvoje 😄

**Comment by f3l1x** [comment]
Maybe related with #19 fix.
